import LoginPage from "../../Pages/loginPage"
import LogoutPage from "../../Pages/LogoutPage"
import MenuElement from "../../Pages/Menu"
import ReportPage from "../../Pages/Report"

let Login = new LoginPage
let Logout = new LogoutPage
let Menu = new MenuElement
let Report = new ReportPage



describe ('Menu Report', () => {

    before('Link Visit', () => {
        cy.visit ('https://apuppt-v5.jiarsi.com/dev/')
        Login.Inputusername('superuser2')
        Login.Inputpassword('Jiarsi1@')
        Login.ClickButtonSignIn()
        cy.wait(4000)
    })

    it('Export Report APUPPT', () => {
        cy.get('.breadcrumb > :nth-child(1) > .text-black').should('be.visible','content.text','Visualization Dashboard')
        Menu.ClickReport()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('User')
        cy.wait(4000)
        Report.ClickUserRole()
        Report.InputDataValue('spv_kp')
        Report.ClickUserBankType()
        Report.InputDataValue('Convent')
        Report.ClickUserBranchName()
        Report.InputDataValue('Kelapa Gading')
        cy.wait(4000)
        //Report.ClickExportButton()
        Report.ClickSelectReport()
        Report.InputDataValue('Account')
        cy.wait(4000)
        cy.xpath ('//input[@id="kt_daterangepicker_5"]').clear()
        cy.wait(4000)
        Report.InputAccountOpeningDate('2020-01-10 - 2023-02-17')
        Report.ClickButtonApply()
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('Branch')
        cy.wait(4000)
        Report.ClickBranchBranchDesc()
        Report.InputDataValue('Cabang Baru')
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('Customer Suspect')
        cy.wait(4000)
        Report.ClickCustomerSuspectBranch()
        Report.InputDataValue('Bank Ganesha')
        Report.ClickCustomerSuspectTypeDesc()
        Report.InputDataValue('Customer Suspected')
        Report.ClickCustomerSuspectStatus()
        Report.InputDataValue('Approved')
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('SIPESAT')
        cy.wait(4000)
        Report.ClickSipesatQuarter()
        Report.InputDataValue('Triwulan 1')
        Report.ClickSipesatYear()
        Report.InputDataValue('2022')
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('Customer Duplicate')
        cy.wait(4000)
        Report.ClickCustomerDuplicateYear()
        Report.InputDataValue('2022')
        Report.ClickCustomerDuplicateMonth()
        Report.InputDataValue('Januari')
        Report.ClickCustomerDuplicateBranchDesc()
        Report.InputDataValue('Ganesha')
        Report.ClickCustomerDuplicateType()
        Report.InputDataValue('Individu')
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('Cash Transaction')
        cy.wait(4000)
        cy.xpath ('//input[@id="kt_daterangepicker_5"]').clear()
        cy.wait(4000)
        Report.InputCTRTransactionDate('2021-01-10 - 2023-02-17')
        Report.ClickCTRButtonApply()
        Report.ClickCTRCustomerType()
        Report.InputDataValue('Corporate')
        Report.ClickCTRBranchDesc()
        Report.InputDataValue('Ganesha')
        //Report.ClickExportButton()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('RBA')
        cy.wait(4000)
        Report.ClickRBABankType()
        Report.InputDataValue('Convent')
        Report.ClickRBABranchName()
        Report.InputDataValue('Cabang Utama')
        Report.ClickRBACustomerType()
        Report.InputDataValue('Individu')
        Report.ClickRBARisktype()
        Report.InputDataValue('High Risk')
         //Report.ClickExportButton()
         cy.wait(4000)
         Report.ClickSelectReport()
         Report.InputDataValue('Unusual Transaction')
         cy.xpath ('//input[@id="kt_daterangepicker_5"]').clear()
         cy.wait(4000)
         Report.InputUTRTransactionDate('2022-01-10 - 2023-02-17')
         Report.ClickUTRButtonApply()
         Report.ClickUTRCustomerType()
         Report.InputDataValue('Individu')
         Report.ClickUTRBrancDesc()
         Report.InputDataValue('Ganesha')
        //Report.ClickExportButton()
        cy.wait(4000)
    })

    it.skip('Export Report APUPPT', () => {
        cy.get('.breadcrumb > :nth-child(1) > .text-black').should('be.visible','content.text','Visualization Dashboard')
        Menu.ClickReport()
        cy.wait(4000)
        Report.ClickSelectReport()
        Report.InputDataValue('Account')
        cy.wait(4000)
        cy.xpath ('//input[@id="kt_daterangepicker_5"]').clear()
        cy.wait(4000)
        Report.InputAccountOpeningDate('2022-01-10 - 2023-02-17')
        Report.ClickButtonApply()
        Report.ClickExportButton()
        cy.wait(4000)

    })

})